/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PremiumSuccessRouteImport } from './routes/premium-success'
import { Route as PremiumChatRouteImport } from './routes/premium-chat'
import { Route as PremiumCancelRouteImport } from './routes/premium-cancel'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWeeklyMatchRouteImport } from './routes/api.weekly-match'
import { Route as ApiTypingRouteImport } from './routes/api.typing'
import { Route as ApiTermsConsentRouteImport } from './routes/api.terms-consent'
import { Route as ApiSubscriptionRouteImport } from './routes/api.subscription'
import { Route as ApiStreakProtectionRouteImport } from './routes/api.streak-protection'
import { Route as ApiReportRouteImport } from './routes/api.report'
import { Route as ApiReactionsRouteImport } from './routes/api.reactions'
import { Route as ApiProfileViewsRouteImport } from './routes/api.profile-views'
import { Route as ApiProfileRouteImport } from './routes/api.profile'
import { Route as ApiPremiumMessagesRouteImport } from './routes/api.premium-messages'
import { Route as ApiCheckUsernameRouteImport } from './routes/api.check-username'
import { Route as ApiNotificationsRouteImport } from './routes/api.notifications'
import { Route as ApiLeaderboardRouteImport } from './routes/api.leaderboard'
import { Route as ApiFriendsRouteImport } from './routes/api.friends'
import { Route as ApiFollowsRouteImport } from './routes/api.follows'
import { Route as ApiDirectMessagesRouteImport } from './routes/api.direct-messages'
import { Route as ApiCommunityMessagesRouteImport } from './routes/api.community-messages'
import { Route as ApiChatRoomsRouteImport } from './routes/api.chat-rooms'
import { Route as ApiChatMessagesRouteImport } from './routes/api.chat-messages'
import { Route as ApiChallengesRouteImport } from './routes/api.challenges'
import { Route as ApiBlocksRouteImport } from './routes/api.blocks'
import { Route as ApiAdminRouteImport } from './routes/api.admin'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/premium-success',
  path: '/premium-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumChatRoute = PremiumChatRouteImport.update({
  id: '/premium-chat',
  path: '/premium-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumCancelRoute = PremiumCancelRouteImport.update({
  id: '/premium-cancel',
  path: '/premium-cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeeklyMatchRoute = ApiWeeklyMatchRouteImport.update({
  id: '/api/weekly-match',
  path: '/api/weekly-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTypingRoute = ApiTypingRouteImport.update({
  id: '/api/typing',
  path: '/api/typing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTermsConsentRoute = ApiTermsConsentRouteImport.update({
  id: '/api/terms-consent',
  path: '/api/terms-consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionRoute = ApiSubscriptionRouteImport.update({
  id: '/api/subscription',
  path: '/api/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreakProtectionRoute = ApiStreakProtectionRouteImport.update({
  id: '/api/streak-protection',
  path: '/api/streak-protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportRoute = ApiReportRouteImport.update({
  id: '/api/report',
  path: '/api/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReactionsRoute = ApiReactionsRouteImport.update({
  id: '/api/reactions',
  path: '/api/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileViewsRoute = ApiProfileViewsRouteImport.update({
  id: '/api/profile-views',
  path: '/api/profile-views',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPremiumMessagesRoute = ApiPremiumMessagesRouteImport.update({
  id: '/api/premium-messages',
  path: '/api/premium-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckUsernameRoute = ApiCheckUsernameRouteImport.update({
  id: '/api/check-username',
  path: '/api/check-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeaderboardRoute = ApiLeaderboardRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFriendsRoute = ApiFriendsRouteImport.update({
  id: '/api/friends',
  path: '/api/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFollowsRoute = ApiFollowsRouteImport.update({
  id: '/api/follows',
  path: '/api/follows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDirectMessagesRoute = ApiDirectMessagesRouteImport.update({
  id: '/api/direct-messages',
  path: '/api/direct-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommunityMessagesRoute = ApiCommunityMessagesRouteImport.update({
  id: '/api/community-messages',
  path: '/api/community-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoomsRoute = ApiChatRoomsRouteImport.update({
  id: '/api/chat-rooms',
  path: '/api/chat-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatMessagesRoute = ApiChatMessagesRouteImport.update({
  id: '/api/chat-messages',
  path: '/api/chat-messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChallengesRoute = ApiChallengesRouteImport.update({
  id: '/api/challenges',
  path: '/api/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlocksRoute = ApiBlocksRouteImport.update({
  id: '/api/blocks',
  path: '/api/blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoute = ApiAdminRouteImport.update({
  id: '/api/admin',
  path: '/api/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/premium': typeof PremiumRoute
  '/premium-cancel': typeof PremiumCancelRoute
  '/premium-chat': typeof PremiumChatRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-rooms': typeof ApiChatRoomsRoute
  '/api/community-messages': typeof ApiCommunityMessagesRoute
  '/api/direct-messages': typeof ApiDirectMessagesRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/check-username': typeof ApiCheckUsernameRoute
  '/api/premium-messages': typeof ApiPremiumMessagesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-views': typeof ApiProfileViewsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/report': typeof ApiReportRoute
  '/api/streak-protection': typeof ApiStreakProtectionRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/terms-consent': typeof ApiTermsConsentRoute
  '/api/typing': typeof ApiTypingRoute
  '/api/weekly-match': typeof ApiWeeklyMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/premium': typeof PremiumRoute
  '/premium-cancel': typeof PremiumCancelRoute
  '/premium-chat': typeof PremiumChatRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-rooms': typeof ApiChatRoomsRoute
  '/api/community-messages': typeof ApiCommunityMessagesRoute
  '/api/direct-messages': typeof ApiDirectMessagesRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/check-username': typeof ApiCheckUsernameRoute
  '/api/premium-messages': typeof ApiPremiumMessagesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-views': typeof ApiProfileViewsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/report': typeof ApiReportRoute
  '/api/streak-protection': typeof ApiStreakProtectionRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/terms-consent': typeof ApiTermsConsentRoute
  '/api/typing': typeof ApiTypingRoute
  '/api/weekly-match': typeof ApiWeeklyMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/friends': typeof FriendsRoute
  '/home': typeof HomeRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/premium': typeof PremiumRoute
  '/premium-cancel': typeof PremiumCancelRoute
  '/premium-chat': typeof PremiumChatRoute
  '/premium-success': typeof PremiumSuccessRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/api/admin': typeof ApiAdminRoute
  '/api/blocks': typeof ApiBlocksRoute
  '/api/challenges': typeof ApiChallengesRoute
  '/api/chat-messages': typeof ApiChatMessagesRoute
  '/api/chat-rooms': typeof ApiChatRoomsRoute
  '/api/community-messages': typeof ApiCommunityMessagesRoute
  '/api/direct-messages': typeof ApiDirectMessagesRoute
  '/api/follows': typeof ApiFollowsRoute
  '/api/friends': typeof ApiFriendsRoute
  '/api/leaderboard': typeof ApiLeaderboardRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/check-username': typeof ApiCheckUsernameRoute
  '/api/premium-messages': typeof ApiPremiumMessagesRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/profile-views': typeof ApiProfileViewsRoute
  '/api/reactions': typeof ApiReactionsRoute
  '/api/report': typeof ApiReportRoute
  '/api/streak-protection': typeof ApiStreakProtectionRoute
  '/api/subscription': typeof ApiSubscriptionRoute
  '/api/terms-consent': typeof ApiTermsConsentRoute
  '/api/typing': typeof ApiTypingRoute
  '/api/weekly-match': typeof ApiWeeklyMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/chat'
    | '/community'
    | '/community-guidelines'
    | '/friends'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/premium'
    | '/premium-cancel'
    | '/premium-chat'
    | '/premium-success'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/api/admin'
    | '/api/blocks'
    | '/api/challenges'
    | '/api/chat-messages'
    | '/api/chat-rooms'
    | '/api/community-messages'
    | '/api/direct-messages'
    | '/api/follows'
    | '/api/friends'
    | '/api/leaderboard'
    | '/api/notifications'
    | '/api/check-username'
    | '/api/premium-messages'
    | '/api/profile'
    | '/api/profile-views'
    | '/api/reactions'
    | '/api/report'
    | '/api/streak-protection'
    | '/api/subscription'
    | '/api/terms-consent'
    | '/api/typing'
    | '/api/weekly-match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/chat'
    | '/community'
    | '/community-guidelines'
    | '/friends'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/premium'
    | '/premium-cancel'
    | '/premium-chat'
    | '/premium-success'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/api/admin'
    | '/api/blocks'
    | '/api/challenges'
    | '/api/chat-messages'
    | '/api/chat-rooms'
    | '/api/community-messages'
    | '/api/direct-messages'
    | '/api/follows'
    | '/api/friends'
    | '/api/leaderboard'
    | '/api/notifications'
    | '/api/check-username'
    | '/api/premium-messages'
    | '/api/profile'
    | '/api/profile-views'
    | '/api/reactions'
    | '/api/report'
    | '/api/streak-protection'
    | '/api/subscription'
    | '/api/terms-consent'
    | '/api/typing'
    | '/api/weekly-match'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/chat'
    | '/community'
    | '/community-guidelines'
    | '/friends'
    | '/home'
    | '/leaderboard'
    | '/login'
    | '/messages'
    | '/premium'
    | '/premium-cancel'
    | '/premium-chat'
    | '/premium-success'
    | '/privacy'
    | '/profile'
    | '/refund-policy'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/api/admin'
    | '/api/blocks'
    | '/api/challenges'
    | '/api/chat-messages'
    | '/api/chat-rooms'
    | '/api/community-messages'
    | '/api/direct-messages'
    | '/api/follows'
    | '/api/friends'
    | '/api/leaderboard'
    | '/api/notifications'
    | '/api/check-username'
    | '/api/premium-messages'
    | '/api/profile'
    | '/api/profile-views'
    | '/api/reactions'
    | '/api/report'
    | '/api/streak-protection'
    | '/api/subscription'
    | '/api/terms-consent'
    | '/api/typing'
    | '/api/weekly-match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  FriendsRoute: typeof FriendsRoute
  HomeRoute: typeof HomeRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  PremiumRoute: typeof PremiumRoute
  PremiumCancelRoute: typeof PremiumCancelRoute
  PremiumChatRoute: typeof PremiumChatRoute
  PremiumSuccessRoute: typeof PremiumSuccessRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  ApiAdminRoute: typeof ApiAdminRoute
  ApiBlocksRoute: typeof ApiBlocksRoute
  ApiChallengesRoute: typeof ApiChallengesRoute
  ApiChatMessagesRoute: typeof ApiChatMessagesRoute
  ApiChatRoomsRoute: typeof ApiChatRoomsRoute
  ApiCommunityMessagesRoute: typeof ApiCommunityMessagesRoute
  ApiDirectMessagesRoute: typeof ApiDirectMessagesRoute
  ApiFollowsRoute: typeof ApiFollowsRoute
  ApiFriendsRoute: typeof ApiFriendsRoute
  ApiLeaderboardRoute: typeof ApiLeaderboardRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiCheckUsernameRoute: typeof ApiCheckUsernameRoute
  ApiPremiumMessagesRoute: typeof ApiPremiumMessagesRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiProfileViewsRoute: typeof ApiProfileViewsRoute
  ApiReactionsRoute: typeof ApiReactionsRoute
  ApiReportRoute: typeof ApiReportRoute
  ApiStreakProtectionRoute: typeof ApiStreakProtectionRoute
  ApiSubscriptionRoute: typeof ApiSubscriptionRoute
  ApiTermsConsentRoute: typeof ApiTermsConsentRoute
  ApiTypingRoute: typeof ApiTypingRoute
  ApiWeeklyMatchRoute: typeof ApiWeeklyMatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-success': {
      id: '/premium-success'
      path: '/premium-success'
      fullPath: '/premium-success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-chat': {
      id: '/premium-chat'
      path: '/premium-chat'
      fullPath: '/premium-chat'
      preLoaderRoute: typeof PremiumChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium-cancel': {
      id: '/premium-cancel'
      path: '/premium-cancel'
      fullPath: '/premium-cancel'
      preLoaderRoute: typeof PremiumCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weekly-match': {
      id: '/api/weekly-match'
      path: '/api/weekly-match'
      fullPath: '/api/weekly-match'
      preLoaderRoute: typeof ApiWeeklyMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/typing': {
      id: '/api/typing'
      path: '/api/typing'
      fullPath: '/api/typing'
      preLoaderRoute: typeof ApiTypingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/terms-consent': {
      id: '/api/terms-consent'
      path: '/api/terms-consent'
      fullPath: '/api/terms-consent'
      preLoaderRoute: typeof ApiTermsConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription': {
      id: '/api/subscription'
      path: '/api/subscription'
      fullPath: '/api/subscription'
      preLoaderRoute: typeof ApiSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/streak-protection': {
      id: '/api/streak-protection'
      path: '/api/streak-protection'
      fullPath: '/api/streak-protection'
      preLoaderRoute: typeof ApiStreakProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/report': {
      id: '/api/report'
      path: '/api/report'
      fullPath: '/api/report'
      preLoaderRoute: typeof ApiReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reactions': {
      id: '/api/reactions'
      path: '/api/reactions'
      fullPath: '/api/reactions'
      preLoaderRoute: typeof ApiReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile-views': {
      id: '/api/profile-views'
      path: '/api/profile-views'
      fullPath: '/api/profile-views'
      preLoaderRoute: typeof ApiProfileViewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/premium-messages': {
      id: '/api/premium-messages'
      path: '/api/premium-messages'
      fullPath: '/api/premium-messages'
      preLoaderRoute: typeof ApiPremiumMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-username': {
      id: '/api/check-username'
      path: '/api/check-username'
      fullPath: '/api/check-username'
      preLoaderRoute: typeof ApiCheckUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/friends': {
      id: '/api/friends'
      path: '/api/friends'
      fullPath: '/api/friends'
      preLoaderRoute: typeof ApiFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/follows': {
      id: '/api/follows'
      path: '/api/follows'
      fullPath: '/api/follows'
      preLoaderRoute: typeof ApiFollowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/direct-messages': {
      id: '/api/direct-messages'
      path: '/api/direct-messages'
      fullPath: '/api/direct-messages'
      preLoaderRoute: typeof ApiDirectMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/community-messages': {
      id: '/api/community-messages'
      path: '/api/community-messages'
      fullPath: '/api/community-messages'
      preLoaderRoute: typeof ApiCommunityMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-rooms': {
      id: '/api/chat-rooms'
      path: '/api/chat-rooms'
      fullPath: '/api/chat-rooms'
      preLoaderRoute: typeof ApiChatRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-messages': {
      id: '/api/chat-messages'
      path: '/api/chat-messages'
      fullPath: '/api/chat-messages'
      preLoaderRoute: typeof ApiChatMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/challenges': {
      id: '/api/challenges'
      path: '/api/challenges'
      fullPath: '/api/challenges'
      preLoaderRoute: typeof ApiChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blocks': {
      id: '/api/blocks'
      path: '/api/blocks'
      fullPath: '/api/blocks'
      preLoaderRoute: typeof ApiBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin': {
      id: '/api/admin'
      path: '/api/admin'
      fullPath: '/api/admin'
      preLoaderRoute: typeof ApiAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  FriendsRoute: FriendsRoute,
  HomeRoute: HomeRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  PremiumRoute: PremiumRoute,
  PremiumCancelRoute: PremiumCancelRoute,
  PremiumChatRoute: PremiumChatRoute,
  PremiumSuccessRoute: PremiumSuccessRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  ApiAdminRoute: ApiAdminRoute,
  ApiBlocksRoute: ApiBlocksRoute,
  ApiChallengesRoute: ApiChallengesRoute,
  ApiChatMessagesRoute: ApiChatMessagesRoute,
  ApiChatRoomsRoute: ApiChatRoomsRoute,
  ApiCommunityMessagesRoute: ApiCommunityMessagesRoute,
  ApiDirectMessagesRoute: ApiDirectMessagesRoute,
  ApiFollowsRoute: ApiFollowsRoute,
  ApiFriendsRoute: ApiFriendsRoute,
  ApiLeaderboardRoute: ApiLeaderboardRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiCheckUsernameRoute: ApiCheckUsernameRoute,
  ApiPremiumMessagesRoute: ApiPremiumMessagesRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiProfileViewsRoute: ApiProfileViewsRoute,
  ApiReactionsRoute: ApiReactionsRoute,
  ApiReportRoute: ApiReportRoute,
  ApiStreakProtectionRoute: ApiStreakProtectionRoute,
  ApiSubscriptionRoute: ApiSubscriptionRoute,
  ApiTermsConsentRoute: ApiTermsConsentRoute,
  ApiTypingRoute: ApiTypingRoute,
  ApiWeeklyMatchRoute: ApiWeeklyMatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
